export const enum ERROR {
  DEFAULT = 'ERROR',
  FILE_NOT_FOUND = 'FILE NOT FOUND',
  INVALID_FILE = 'INVALID FILE',
  INVALID_NUMBER_OF_ARGUMENTS = 'INVALID NUMBER OF ARGUMENTS',
  INVALID_SYNTAX = 'INVALID SYNTAX'
};
